var normal = 'hola';
normal = 10;
normal = true;
var usuario = 20;
console.log(normal);
var nombre = 'Juan';
nombre = 'Juan Carlos';
console.log(nombre);
var value;
console.log(value);
value = true;
value = 10;
value = 'hola';
value = [];
value = {};
value = Math.random;
value = null;
value = undefined;
console.log(value);
var mivalor;
console.log("Tipo unknown", mivalor);
var value1 = mivalor;
var value2 = mivalor;
// let value3: boolean = mivalor; //Error
// let value4: number = mivalor; //Error
var edad = 18;
console.log("Edad", edad);
console.log("Edad" + edad);
var sueldo = 1.1234;
var total = Number('5678');
console.log("Sueldo", sueldo);
console.log("Total", total);
var personaje = 'El chavo';
var p2 = 'Don Ramon';
var p3 = "Quico y ".concat(personaje);
console.log(p3);
//const antiHero:string = 'Deadpool's house'; // error
var antiHero = "Deadpool\'s house";
console.log(antiHero);
console.log(antiHero.toLocaleUpperCase());
var vengador;
vengador = 'Dr. Strange';
console.log(vengador.chartAt(0));
vengador = 150.55;
console.log(vengador.toFixed(1));
console.log(vengador.toFixed(1));
console.log(vengador.toFixed(1));
var personas = ['Carlos', 'Juan', 'Pedro'];
console.log(personas);
console.log(personas[0]);
console.log(personas[3]);
console.log(personas[-1]);
personas.push('Maria');
console.log(personas);
var numeros = [1, 2, 3, 4, 5];
var numeros2 = [6, 7, 8, 9, 10];
console.log(numeros, numeros2);
var numerosCadena = document.getElementById("numeros");
for (var i = 0; i < numerosCadena.length; i++) {
    numerosCadena.innerHTML += numeros[i] + " ";
}
